# Generated by Django 4.2.6 on 2023-11-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoop', '0004_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
